
create table forma_pagamento (
	id bigint generated by default as identity,
	descricao varchar(60),
	primary key (id)
	);


create table grupo (
	id bigint generated by default as identity,
	descricao varchar(60),
	primary key (id)
);

create table grupo_permissoes (
	grupo_id bigint not null,
	permissao_id bigint not null
);



create table permissao (
	id bigint generated by default as identity,
	descricao varchar(60),
	nome varchar(30),
	primary key (id)
);


create table produto (
	id bigint generated by default as identity,
	ativo boolean not null, descricao varchar(60),
	nome varchar(60),
	preco numeric(19,2),
	restaurante_id bigint,
	primary key (id)
);


create table restaurante (
	id bigint generated by default as identity,
	data_atualizacao timestamp not null,
	data_cadastro timestamp not null,
	endereco_bairro varchar(60),
	endereco_cep varchar(60),
	endereco_complemento varchar(60),
	endereco_logradouro varchar(60),
	endereco_numero varchar(60),
	nome varchar(60) not null,
	taxa_frete numeric(19,2) not null,
	cozinha_id bigint not null,
	endereco_cidade_id bigint,
	primary key (id)
);
 
 
create table restaurante_forma_pagamento (
	restaurante_id bigint not null,
	forma_pagamento_id bigint not null
);


create table usuario (
	id bigint generated by default as identity,
	data_cadatro timestamp,
	email varchar(60),
	nome varchar(60),
	senha varchar(60),
	primary key (id)
);

create table usuario_grupo (
	usuario_id bigint not null,
	grupo_id bigint not null
	);

alter table grupo_permissoes add constraint fk_grupo_permissao_permissao foreign key (permissao_id) references permissao(id);
alter table grupo_permissoes add constraint fk_grupo_permissao_grupo foreign key (grupo_id) references grupo(id);
alter table produto add constraint fk_produto_restaurante foreign key (restaurante_id) references restaurante(id);
alter table restaurante add constraint fk_restaurante_cozinha foreign key (cozinha_id) references cozinha(id);
alter table restaurante add constraint fk_restaurante_cidade foreign key (endereco_cidade_id) references cidade(id);
alter table restaurante_forma_pagamento add constraint fk_rest_forma_pagto_forma_pagto foreign key (forma_pagamento_id) references forma_pagamento(id);
alter table restaurante_forma_pagamento add constraint fk_rest_forma_pagto_restaurante foreign key (restaurante_id) references restaurante(id);
alter table usuario_grupo add constraint fk_usuario_grupo_grupo foreign key (grupo_id) references grupo(id);
alter table usuario_grupo add constraint fk_usuario_grupo_usuario foreign key (usuario_id) references usuario(id);
