
create table item_pedido (
	id bigint generated by default as identity, observacao varchar(255),
	preco_total numeric(19,2),
	preco_unitario numeric(19,2),
	quantidade integer,
	pedido_id bigint not null,
	produto_id bigint not null,
	primary key (id)
	);
create table pedido (
	id bigint generated by default as identity,
	data_cancelamento timestamp,
	data_confirmacao timestamp,
	data_criacao timestamp,
	data_entrega timestamp,
	endereco_bairro varchar(255),
	endereco_cep varchar(255),
	endereco_complemento varchar(255),
	endereco_logradouro varchar(255),
	endereco_numero varchar(255),
	status integer, subtotal numeric(19,2),
	taxa_frete numeric(19,2), valor_total numeric(19,2),
	usuario_cliente_id bigint not null,
	endereco_cidade_id bigint,
	forma_pagamento_id bigint not null,
	restaurante_id bigint not null, primary key (id));

alter table item_pedido add constraint fk_item_pedido_pedid foreign key (pedido_id) references pedido(id);
alter table item_pedido add constraint fk_item_pedido_produto foreign key (produto_id) references produto(id);
alter table pedido add constraint fk_pedido_usuario_cliente foreign key (usuario_cliente_id) references usuario(id);

alter table pedido add constraint fk_pedido_forma_pagamento foreign key (forma_pagamento_id) references forma_pagamento(id);
alter table pedido add constraint fk_pedido_restaurante foreign key (restaurante_id) references restaurante(id);